### PR TITLE
Turn off some warnings for QoS for gcc13

### PR DESCRIPTION
**Pull request by doug1234**
Note:  These warnings could be due to issues with OpenDDS but turn them off for now.

### CODE REVIEW

**Review by mitza-oci — CHANGES_REQUESTED** [review]
Do you have a link to the warning that this is preventing?  I'll check if we can fix it in OpenDDS.

The new code is generating its own warning on compilers that don't have a `-Wstringop-overflow`, so this may need to be conditional on the specific compiler/version:
https://github.com/OpenDDS/OpenDDW/actions/runs/15005619676/job/42163404066?pr=42#step:24:61

**Comment by doug1234** [comment]
```
In static member function ‘static _Up* std::__copy_move<_IsMove, true, std::random_access_iterator_tag>::__copy_m(_Tp*, _Tp*, _Up*) [with _Tp = short int; _Up = short int; bool _IsMove = false]’,
    inlined from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = short int*; _OI = short int*]’ at /opt/rh/gcc-toolset-13/root/usr/include/c++/13/bits/stl_algobase.h:506:30,
    inlined from ‘_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = false; _II = short int*; _OI = short int*]’ at /opt/rh/gcc-toolset-13/root/usr/include/c++/13/bits/stl_algobase.h:533:42,
    inlined from ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = short int*; _OI = short int*]’ at /opt/rh/gcc-toolset-13/root/usr/include/c++/13/bits/stl_algobase.h:540:31,
    inlined from ‘_OI std::copy(_II, _II, _OI) [with _II = short int*; _OI = short int*]’ at /opt/rh/gcc-toolset-13/root/usr/include/c++/13/bits/stl_algobase.h:633:7,
    inlined from ‘static void TAO::details::value_traits<T, dummy>::copy_range(value_type*, value_type*, iter) [with iter = short int*; T = short int; bool dummy = true]’ at /sandbox/gitlab-runner-ibst/builds/ibst/products/open-source/OpenDDW/spm-rhel9-gcc13/open-source/opendds/include/tao/Value_Traits_T.h:52:14,
    inlined from ‘static void TAO::details::value_traits<T, dummy>::copy_swap_range(value_type*, value_type*, iter) [with iter = short int*; T = short int; bool dummy = true]’ at /sandbox/gitlab-runner-ibst/builds/ibst/products/open-source/OpenDDW/spm-rhel9-gcc13/open-source/opendds/include/tao/Value_Traits_T.h:60:15,
    inlined from ‘void TAO::details::generic_sequence<T, ALLOCATION_TRAITS, ELEMENT_TRAITS>::length(CORBA::ULong) [with T = short int; ALLOCATION_TRAITS = TAO::details::unbounded_value_allocation_traits<short int, true>; ELEMENT_TRAITS = TAO::details::value_traits<short int, true>]’ at /sandbox/gitlab-runner-ibst/builds/ibst/products/open-source/OpenDDW/spm-rhel9-gcc13/open-source/opendds/include/tao/Generic_Sequence_T.h:239:36,
    inlined from ‘void TAO::details::generic_sequence<T, ALLOCATION_TRAITS, ELEMENT_TRAITS>::length(CORBA::ULong) [with T = short int; ALLOCATION_TRAITS = TAO::details::unbounded_value_allocation_traits<short int, true>; ELEMENT_TRAITS = TAO::details::value_traits<short int, true>]’ at /sandbox/gitlab-runner-ibst/builds/ibst/products/open-source/OpenDDW/spm-rhel9-gcc13/open-source/opendds/include/tao/Generic_Sequence_T.h:198:8,
    inlined from ‘void TAO::unbounded_value_sequence<T, Tag>::length(CORBA::ULong) [with T = short int; Tag = int]’ at /sandbox/gitlab-runner-ibst/builds/ibst/products/open-source/OpenDDW/spm-rhel9-gcc13/open-source/opendds/include/tao/Unbounded_Value_Sequence_T.h:60:17,
    inlined from ‘void {anonymous}::init(DDS::TopicQos&)’ at /sandbox/gitlab-runner-ibst/builds/ibst/products/open-source/OpenDDW/OpenDDW/src/qos_dictionary.cpp:54:40,
    inlined from ‘DDS::TopicQos QosDictionary::Topic::bestEffort()’ at /sandbox/gitlab-runner-ibst/builds/ibst/products/open-source/OpenDDW/OpenDDW/src/qos_dictionary.cpp:228:9:
/opt/rh/gcc-toolset-13/root/usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ forming offset 2 is out of the bounds [0, 2] [-Werror=array-bounds=]
  437 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by iguessthislldo** [comment]
If we can't fix in OpenDDS, we can [check for the warning](https://stackoverflow.com/questions/42979987/use-pragma-to-disable-a-warning-if-implemented) so it doesn't cause warnings in other compilers.

**Comment by iguessthislldo** [comment]
What was wrong with https://github.com/OpenDDS/OpenDDW/pull/42/commits/65b076f1af9d6fd8b4390ffeb070c99cce39fab2? It looks correct to me and I didn't see any warnings on it.

**Comment by doug1234** [comment]
It didn't seem to work with gcc13 so it didn't fix the original problem sadly.  The latest actually works.

**Comment by mitza-oci** [comment]
> It didn't seem to work with gcc13 so it didn't fix the original problem sadly. The latest actually works.

Is that issue with GCC 13 visible in the CI builds on ubuntu-24.04 (GCC 13 is the default version on Ubuntu 24.04)?  If not, is there a configuration change we could make in the CI?

File: src/qos_dictionary.cpp [hunk 1]
```diff
@@ -1,19 +1,25 @@
...
 
 #include "qos_dictionary.h"
 
 #include <iostream>
 #include <string>
 
+//gcc13 warnings from OpenDDS
+#if !defined(__clang__) && !defined(WIN32)
+#    pragma GCC diagnostic ignored "-Warray-bounds"
+#      pragma GCC diagnostic ignored "-Wstringop-overflow"
```
Comment (mitza-oci) [inline src/qos_dictionary.cpp]:
```suggestion
#    pragma GCC diagnostic ignored "-Wstringop-overflow"
```

**Comment by doug1234** [comment]
I had the issue when I built locally with gcc13.  It looks like you are using gcc11 unless I am looking at the wrong thing.  `The CXX compiler identification is GNU 11.4.0`

**Comment by mitza-oci** [comment]
> I had the issue when I built locally with gcc13. It looks like you are using gcc11 unless I am looking at the wrong thing. `The CXX compiler identification is GNU 11.4.0`

22.04 is GCC 11; 24.04 is GCC 13

https://github.com/OpenDDS/OpenDDW/actions/runs/15076340483/job/42384505992#step:24:27

**Comment by doug1234** [comment]
Hum... I am confused then.  It seems that you never got this warning with gcc13 in CI?

**Comment by iguessthislldo** [comment]
> It didn't seem to work with gcc13 so it didn't fix the original problem sadly. The latest actually works.

I looked at the stackoverflow link again and discovered `__has_warning` is Clang only. My bad for linking something that didn't work in this situation.

**Comment by doug1234** [comment]
@iguessthislldo that makes sense but how come we are not seeing the warnings on the gcc13 build through CI.  I see them when I build with gcc13 so its odd.

**Comment by mitza-oci** [comment]
I didn't see the warning in a local build with GCC 14 (I don't happen to have 13 installed on that particular VM anymore).
I may also have a different version of TAO but I think this code is essentially the same.

As far as I can tell the warning from the compiler isn't meaningful and can be ignored.  That's just a theory, but if we ran an OpenDDW-using program through valgrind or asan it might help to validate.

**Review by mitza-oci — APPROVED** [review]
